services:
  app:
    command: sh docker/node/entrypoint.sh
    volumes:
      - .:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules
      - client_node_modules:/usr/src/app/client/node_modules
    healthcheck:
      start_period: 120s

  nginx:
    volumes:
      - ./public:/usr/src/app/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  database:
    ports:
      - '5432'

  mailer:
    image: axllent/mailpit
    ports:
      - '1025'
      - '8025'
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  node_modules:
  client_node_modules:
